# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vrm6d3GdR1me-PcOmAWr6EJmaIVxa65A
"""

lista = list(input("Escribe la serie de datos deseados").split(" "))
vacia = []
for ola in lista:
  if ola not in vacia:
    vacia.append(ola)
    print(ola, end = " ")