# -*- coding: utf-8 -*-
"""Progra

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaR-76ZQCTnnbkBALvAZU3Hp-ZxdLAPw

Pide al usuario el total de una cuenta y el porcentaje de propina
(por ejemplo, 10%, 15%, 20%). Calcula y muestra en pantalla el total
a pagar.
• El formato de la salida debe ser (el ejemplo asume un total de $10
y 10% de propina)
"""

prop = int(input("Ingresa el porcentaje de porpina deseado: "))
propr = prop/100
precio = float(input("Ingrese el total sin propina"))

propp = precio*propr

total = propp + precio

print(total)

"""1.3.2. Generador del correo de Key
Solicita al usuario su nombre completo (asume dos nombres y
dos apellidos). Luego, el programa generará, su correo con el
formato:
• primer_nombre.primer_apellido@keyinstitute.edu.sv
Finalmente, el programa mostrará en pantalla el siguiente
mensaje:
21
El correo que se debe asignar al usuario ingresado es:
nombre.apellido@keyinstitute.edu.sv
"""

Nombrecompleto = input("Ingrese su nombre completo ")
A = Nombrecompleto.lower()
N = A.split()
pn = N[0]
pa = N[2]
print(f"{pn}.{pa}@keyinstitute.edu.sv")

"""Solicita una cadena de texto que representa una contraseña, y verifica si la contraseña
cumple con las siguientes condiciones: tener al menos 8 caracteres, un número y una
mayúscula.
Entrada:
• Una cadena de texto
Salida:
• Dos posibles valores: "Contraseña segura" o "Contraseña no segura".
Restricciones:
• Sin restricciones
Sugerencia:
• Investigar sobre los métodos isdigit() y isupper()
16

"""

con= input("Ingrese su contrasena")
num = any(char.isdigit() for char in con)



if con.islower():
  print("Contraseña Invalida")
elif num != True:
  print("Contraseña Invalida")
elif len(con) < 8:
  print("Contrasena Invalida")
else:
  print("Contraseña Valida")

"""Desarrollar un programa en Python que permita calcular el impuesto que debe pagar
un usuario por el consumo de energía. El cálculo debe realizarse basado en la siguiente
tabla.
Entrada:
• Unidades consumidas (entero).
Salida:
• Impuesto aplicado ($).
Restricciones:
• Sin restricciones.
"""

cons = int(input("Ingrese su pago por consumo de energia"))
if cons > 0 and cons <= 100:
  print("Sin Impuestos")
elif cons > 100 and cons <= 200:
  print("$0.5 por c/unidad")
elif cons > 200 :
  print("$0.7 por c/unidad")